import Head from "next/head";
import formRegistro from "@/Components/Forms/formRegistro";
import MyHeader from "@/Components/myHeader";
import styles from "@/styles/Home.module.css";
import Form from 'react-bootstrap/Form';



export default function Registro() {
    return (
        <>
            <Head>
                 <title>Pedi Ya comida en instantes</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/LogoP.png" />
                <link
                    rel="stylesheet"
                    href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
                    integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
                    crossorigin="anonymous"
                /> 
            </Head>
            <MyHeader></MyHeader>
            <main className={`${styles.main}`}>
            
            <formRegistro>Formulario</formRegistro>
            <Form>
      <Form.Group className="mb-3" controlId="exampleForm.ControlInput1">
        <Form.Label>Email</Form.Label>
        <Form.Control type="email" placeholder="name@example.com" />
      </Form.Group>
      <Form.Group className="mb-3" controlId="exampleForm.ControlTextarea1">
        <Form.Label>Algo acerca de tu negocio</Form.Label>
        <Form.Control as="textarea" rows={3} />
      </Form.Group>
    </Form>
            </main>
        </>
    )
}